Features/switch
pilotpirxie/react-toucan-ui pull request #8
Opened 2022-10-30 20:40 UTC by yinchyy

2022-11-04 23:15 UTC, pilotpirxie approved these changes

2022-11-04 23:15 UTC, pilotpirxie commented on scripts/build.sh
> +sed -i -E '/devDependencies/,/}/{/"react"|"react-dom"/d}' package.json && yarn && rollup -c && sed -i -e '23a\' -e '    "react": "\^18.2.0"\,\n    "react-dom": "\^18.2.0"\,' package.json && yarn
IMO split with \ per line to make it easier readable

2022-11-04 23:15 UTC, pilotpirxie commented on src/Checkbox/Checkbox.tsx
> +      className={cx({ [styles.checkbox]: true })}
hmm isn't this always true? so you can 
```
 className={styles.checkbox}
```

2022-11-04 23:15 UTC, pilotpirxie commented on src/Switch/Switch.tsx
> +  checked?: boolean;
In checkbox you have ``defaultChecked`` make it consistent.

2022-11-04 23:15 UTC, pilotpirxie commented on src/Switch/Switch.tsx
> +        [styles.switch]: true,
it's always true so you can
```
cx(styles.switch, {
[styles.outlinePrimary]: isChecked,
[styles.outlineSecondary]: !isChecked,
})
```

No need to pass true

2022-11-04 23:15 UTC, pilotpirxie commented on src/Switch/switch.module.scss
> +    position: absolute;
is this position absolute necessary?

2022-11-04 23:15 UTC, pilotpirxie requested changes
^

2022-11-04 23:15 UTC, pilotpirxie commented
@yinchyy

2022-11-05 07:44 UTC, yinchyy commented on scripts/build.sh
> +sed -i -E '/devDependencies/,/}/{/"react"|"react-dom"/d}' package.json && yarn && rollup -c && sed -i -e '23a\' -e '    "react": "\^18.2.0"\,\n    "react-dom": "\^18.2.0"\,' package.json && yarn
resolved [e6d4049](https://github.com/pilotpirxie/react-toucan-ui/pull/8/commits/e6d4049f5c6515106dd7bb2f5c846be8f6b8f34a)

2022-11-05 07:57 UTC, yinchyy commented on src/Checkbox/Checkbox.tsx
> +      className={cx({ [styles.checkbox]: true })}
resolved [c203084](https://github.com/pilotpirxie/react-toucan-ui/pull/8/commits/c20308454c438b19459f1dbe29cfc1dd8ae1c704)

2022-11-05 07:57 UTC, yinchyy commented on src/Switch/Switch.tsx
> +  checked?: boolean;
resolved [c203084](https://github.com/pilotpirxie/react-toucan-ui/pull/8/commits/c20308454c438b19459f1dbe29cfc1dd8ae1c704)

2022-11-05 07:57 UTC, yinchyy commented on src/Switch/Switch.tsx
> +        [styles.switch]: true,
resolved [c203084](https://github.com/pilotpirxie/react-toucan-ui/pull/8/commits/c20308454c438b19459f1dbe29cfc1dd8ae1c704)

2022-11-05 09:45 UTC, yinchyy commented on src/Switch/switch.module.scss
> +    position: absolute;
It isn't :smile: 
changed to transform: translate()
[dfde1d1](https://github.com/pilotpirxie/react-toucan-ui/pull/8/commits/dfde1d1e1399dba8a80e1411d1ff6433c0067c72)

2022-11-05 11:27 UTC, pilotpirxie approved these changes

2022-11-05 11:28 UTC, merged